import questionBankData from "@/data/generated/ask-question-bank.json";

// Task F13b: single source of truth for the Ask Portfolio launcher's route-aware
// preset questions. `src/data/generated/ask-question-bank.json` is generated by
// `scripts/generate-ask-question-bank.mjs` (task F13a) from
// `assistant-knowledge/question-bank.json`, and every question in it has already
// been proven answerable-with-citations by `tests/assistant/ask-question-bank.test.mjs`.
// This module is the only place that reads that artifact for UI presets; both the
// floating assistant launcher/panel (AssistantWidget) and the homepage inline "Ask
// Portfolio" surface (AskPortfolioInline) resolve their preset chips through it
// instead of carrying their own copies.

export interface AskQuestionBankEntry {
  id: string;
  q_en: string;
  q_zh: string;
}

interface AskQuestionBankRoute {
  questions: AskQuestionBankEntry[];
}

type AskQuestionBank = Record<string, AskQuestionBankRoute>;

const questionBank = questionBankData as AskQuestionBank;

export const ASK_QUESTION_BANK_HOME_ROUTE = "/";

const homeEntry = questionBank[ASK_QUESTION_BANK_HOME_ROUTE];
if (!homeEntry) {
  throw new Error(`ask-question-bank.json is missing its "${ASK_QUESTION_BANK_HOME_ROUTE}" fallback route`);
}

// Route matching is exact-path only: `pathname` is always the fully resolved
// route (e.g. `usePathname()` returns "/ai/release-guardian" whether that page
// is served by its own static route folder or by the shared
// `src/app/[track]/[project]/page.tsx` dynamic route), and the bank's keys are
// the same literal route strings the generator derived from
// `assistant-knowledge/manifest.json`'s `siteSources`. Any route the bank
// doesn't carry — an unbanked track index page like `/ai`, `/artifact`, or a
// future page — falls back to the home/general question set.
export function getRouteQuestionBankEntries(pathname: string): AskQuestionBankEntry[] {
  return (questionBank[pathname] ?? homeEntry).questions;
}

export function getRouteQuestions(pathname: string, locale: "en" | "zh"): string[] {
  return getRouteQuestionBankEntries(pathname).map((entry) => (locale === "en" ? entry.q_en : entry.q_zh));
}

export function getHomeQuestions(locale: "en" | "zh"): string[] {
  return getRouteQuestions(ASK_QUESTION_BANK_HOME_ROUTE, locale);
}
