// Centralized Playwright selector contract for tests/e2e/**/*.spec.ts.
//
// This file exists so the upcoming UI rebuild only has to update selector VALUES
// here, not hunt through every spec file. Content/text assertions are untouched.
//
// `rail`, `exhibit`, `projectSection`, and `instrument` are the frozen interface for
// FUTURE components (data-exhibition-rail / data-exhibit / data-project-section /
// data-instrument). `data-exhibit` and `data-project-section` already exist in the
// current markup, so their current usages are expressed via these functions below.
// Every other constant is the current CSS selector for existing structural markup,
// collected here verbatim; it will be remapped in place during the rebuild.

export const SEL = {
  // --- Frozen interface for future exhibition-grammar components ---
  rail: '[data-exhibition-rail]',
  exhibit: (n: string) => `[data-exhibit="${n}"]`,
  projectSection: (k: string) => `[data-project-section="${k}"]`,
  instrument: '[data-instrument]',
  // Bare attribute form (no key), used where a test only checks presence.
  projectSectionAttr: '[data-project-section]',

  // --- Dynamic (parameterized) structural selectors ---
  optionWithValue: (value: string) => `option[value="${value}"]`,
  creditVintageButton: (vintage: string) => `.credit-vintages button[title^="${vintage}:"]`,
  linkWithHref: (href: string) => `a[href="${href}"]`,

  // --- Existing structural selectors (collected as-is; values will change in the rebuild) ---
  // Task 0.5: the deleted site-header's brand-mark/home link is re-homed as
  // a single-mount "Home" link in the exhibition rail's tools slot (see
  // src/components/exhibition/LegacyRailTools.tsx), not duplicated per
  // breakpoint the way the rail's own nav/footer lists are.
  aBrand: 'a.rail-home-link',
  aHrefAiReleaseGuardian: 'a[href="/ai/release-guardian"]',
  aHrefArtifactHrefWorkstationReproductionGuideMd: 'a[href^="/artifact?"][href*="workstation-reproduction-guide.md"]',
  aHrefGithubComLuciszhang: 'a[href="https://github.com/LucisZhang"]',
  aHrefGithubComLuciszhangExactlyOnceDrills: 'a[href="https://github.com/LucisZhang/exactly-once-drills"]',
  aHrefGithubComLuciszhangReleaseGuardian: 'a[href="https://github.com/LucisZhang/release-guardian"]',
  aHrefMailtoHsiangkuochangoutlookCom: 'a[href="mailto:HsiangKuoChang@outlook.com"]',
  aHrefResumePdf: 'a[href="/resume.pdf"]',
  aHrefWwwLinkedinComInXiangguoZhang: 'a[href="https://www.linkedin.com/in/xiangguo-zhang"]',
  analyticsContractGrid: '.analytics-contract-grid',
  analyticsContractGridPPass: '.analytics-contract-grid p.pass',
  analyticsControlbarSelect: '.analytics-controlbar select',
  analyticsDatasetContextDd: '.analytics-dataset-context dd',
  analyticsFieldGrid: '.analytics-field-grid',
  analyticsLabFooterCode: '.analytics-lab-footer code',
  analyticsMigration: '.analytics-migration',
  analyticsMigrationAHrefAnalyticsCreditPolicyDesk: '.analytics-migration a[href="/analytics/credit-policy-desk"]',
  analyticsMigrationAHrefAnalyticsMarginControlTower: '.analytics-migration a[href="/analytics/margin-control-tower"]',
  analyticsOfflinePanel: '.analytics-offline-panel',
  analyticsQualityListPass: '.analytics-quality-list .pass',
  analyticsQualityListPPass: '.analytics-quality-list p.pass',
  article: 'article',
  artifactError: '.artifact-error',
  artifactErrorSmall: '.artifact-error small',
  artifactFilterbar: '.artifact-filterbar',
  artifactImageViewerImg: '.artifact-image-viewer img',
  artifactMarkdownH1: '.artifact-markdown h1',
  artifactMarkdownLayoutAsideAHref: '.artifact-markdown-layout aside a[href^=\'#\']',
  artifactMermaidSvgSvg: '.artifact-mermaid-svg svg',
  artifactPageHeader: '.artifact-page-header',
  artifactPageHeaderDivFirstChildPNotEyebrow: '.artifact-page-header > div:first-child > p:not(.eyebrow)',
  artifactPdfCanvasCanvas: '.artifact-pdf-canvas canvas',
  artifactPdfControls: '.artifact-pdf-controls',
  artifactRawSource: '.artifact-raw-source',
  artifactTableA: '.artifact-table > a',
  artifactZoomControlsOutput: '.artifact-zoom-controls output',
  body: 'body',
  // Task 0.5: the deleted site-header's "XGZ" mono mark is now the
  // exhibition rail's wordmark mark (src/components/exhibition/legacyRail.ts
  // sets wordmark.mark to the same "XGZ" text).
  brandMark: '.exhibit-rail-mark',
  buttonDataFilterTraining: 'button[data-filter="training"]',
  canvas: 'canvas',
  caseTitleCnGloss: '.case-title .cn-gloss',
  caseTitleLede: '.case-title .lede',
  classPromptsButton: '[class*=\'prompts\'] button',
  cmdkItem: '[cmdk-item]',
  cnGloss: '.cn-gloss',
  codeTitle: 'code[title]',
  commandCompletions: '.command-completions',
  commandDialog: '.command-dialog',
  commandEmpty: '.command-empty',
  commandSearchNote: '.command-search-note',
  commandSuggestionsButton: '.command-suggestions button',
  creditAuditRecord: '.credit-audit-record',
  creditCalibration: '.credit-calibration',
  creditDecisionBandsDiv: '.credit-decision-bands > div',
  creditDecisionBoundary: '.credit-decision-boundary',
  creditEntityLedgerCode: '.credit-entity-ledger code',
  creditLayerStripDiv: '.credit-layer-strip > div',
  creditPolicyGuidance: '.credit-policy-guidance',
  creditQueueGridSection: '.credit-queue-grid section',
  creditScoreChainDiv: '.credit-score-chain > div',
  dataCountBareTransport: '[data-count="bare-transport"]',
  dataCountGateway429: '[data-count="gateway-429"]',
  dataPdfPage: '[data-pdf-page]',
  dataPdfPage1: '[data-pdf-page="1"]',
  dataResultNegative: '[data-result="negative"]',
  dataSeriesBareVllm: '[data-series="bare-vllm"]',
  dataSeriesGateway: '[data-series="gateway"]',
  evidenceLinkA: '.evidence-link a',
  figcaption: 'figcaption',
  figureDataEvidenceKindPresentationLayerDerivative: 'figure[data-evidence-kind="presentation-layer-derivative"]',
  findingTableDivNotFindingHead: '.finding-table > div:not(.finding-head)',
  // Task W1: hero's old .forge-honesty-note line was replaced by the
  // reference-composition .forge-scope-note (.forge-honesty-note itself
  // stays defined in ProjectPageView.module.css for CaseStudyBlock's
  // separate legacy project-page rendering, untouched by this task).
  forgeHonestyNote: '.forge-scope-note',
  forgeReplayReceiptBoundary: '.forge-replay-receipt-boundary',
  h1: 'h1',
  // Task 1.2 (homepage seven-exhibit rebuild): the hero is now exhibit 00,
  // reusing the shared .exhibit-eyebrow/.exhibit-title primitives inside
  // .home-hero rather than the pre-rebuild .eyebrow/.lede/.hero-evidence
  // markup those classes used to point at.
  homeHero: '.home-hero',
  homeHeroEyebrow: '.home-hero .exhibit-eyebrow',
  homeHeroTitle: '#hero-title',
  homeHeroZh: '.home-hero-zh',
  homeHeroContactLink: '.home-hero-contact a, .home-hero-contact button',
  homeCta: '.home-cta',
  homeClaimChain: '.home-claim-chain',
  homeClaimRow: '.home-claim-row',
  homeClaimValue: '.home-claim-value',
  homeAgentRow: '.home-agent-row',
  homeAskInput: '.home-ask input',
  homeAskPresetButton: '.home-ask-presets button',
  homeStackLayer: '.home-stack-layer',
  homeEodCell: '.home-eod-cell',
  homeNegativeRow: '.home-negative-row',
  homeShelfRow: '.home-shelf-row',
  homeReceiptsDl: '.home-receipts-dl',
  homeRailTools: '.home-rail-tools',
  // Task F14: the SEARCH ⌘K / EN·中 / contact trio on the 10 standalone
  // project routes (ProjectRailTools.tsx) — home's rail-footer sibling.
  projectRailTools: '.project-rail-tools',
  html: 'html',
  i: 'i',
  img: 'img',
  input: 'input',
  inputTypeFile: 'input[type="file"]',
  jsonNodeSummarySmall: '.json-node summary small',
  jsonTree: '.json-tree',
  jsonTreeJsonNodeSummary: '.json-tree > .json-node > summary',
  linkListAHrefGithubComNotHref: '.link-list a[href^="https://github.com/"]:not([href*="#"])',
  main: 'main',
  mainHeaderH1: 'main header h1',
  mainHeaderLede: 'main header .lede',
  marginAction: '.margin-action',
  marginActionCode: '.margin-action code',
  marginBeforeAfter: '.margin-before-after',
  marginHeatmapGridButton: '.margin-heatmap-grid button',
  marginWeekBarsButton: '.margin-week-bars button',
  mediaGridFigure: '.media-grid figure',
  metaNameDescription: 'meta[name="description"]',
  metaNameRobots: 'meta[name="robots"]',
  metricsChipsSmall: '.metrics-chips small',
  metricTableSvg: '.metric-table svg',
  notesSection: '.notes-section',
  notesSectionH2: '.notes-section h2',
  option: 'option',
  privacyBenchmarkSummary: '.privacy-benchmark-summary',
  privacyBoxListArticle: '.privacy-box-list article',
  privacyBoxListArticleCode: '.privacy-box-list article code',
  privacyBoxListArticleInput: '.privacy-box-list article input',
  privacyCanvasWrapCanvas: '.privacy-canvas-wrap canvas',
  privacyComparisonGrid: '.privacy-comparison-grid',
  privacyComparisonItem: '.privacy-comparison-item',
  // Task F6 (direction B, "the document is the interface"): the exhibit-01
  // text workspace's old entity-review cards (.privacy-entity et al.) are
  // retired along with every other fine-grained review control -- the
  // reviewer's only move now is clicking a strike directly in the working
  // copy. See PrivacyTextLab.tsx / task-F6-report.md.
  privacyDocStrike: '.doc-strike',
  privacyGalleyDoc: '[data-testid="privacy-galley-doc"]',
  privacyNote: '.privacy-note',
  privacySafeOutput: '[data-testid="privacy-safe-output"]',
  privacyVerdict: '[data-testid="privacy-verdict"]',
  privacyVerdictFail: '[data-testid="privacy-verdict"].fail',
  privacyVerdictPass: '[data-testid="privacy-verdict"].pass',
  privacyActionLine: '.privacy-action-line',
  privacyScanLink: '.privacy-scan-link',
  privacySampleLink: '.privacy-sample-link',
  privacyError: '.privacy-error',
  privacyExampleStatus: '.privacy-example-status',
  privacyFileName: '.privacy-file-name',
  privacyMacosStatus: '#privacy-macos-status',
  privacyOcrStatus: '.privacy-ocr-status',
  privacyPageCounter: '.privacy-page-counter',
  privacyPageMethod: '.privacy-page-method',
  privacyPageTabs: '.privacy-page-tabs',
  privacyPdfCanvasStackCanvas: '.privacy-pdf-canvas-stack canvas',
  privacyPdfCanvasWrap: '.privacy-pdf-canvas-wrap',
  privacyPdfChecksSpan: '.privacy-pdf-checks span',
  privacyPdfWorkspacePrivacyActionbarPrivacyPageCounter: '.privacy-pdf-workspace > .privacy-actionbar .privacy-page-counter',
  privacyScanHint: '.privacy-scan-hint',
  // Still used by the Image/PDF workspaces, whose pass/fail state keeps the
  // shared .privacy-validation class this round (only their chrome, not
  // their markup, changed).
  privacyValidation: '.privacy-validation',
  privacyValidationFail: '.privacy-validation.fail',
  privacyValidationPass: '.privacy-validation.pass',
  privacyVerificationMetrics: '.privacy-verification-metrics',
  projectOutcome: '.project-outcome',
  projectStatGridDiv: '.project-stat-grid > div',
  projectSummary: '.project-summary',
  projectTitle: '#project-title',
  // Task 0.5: ProjectProofSection no longer wraps its content in an inner
  // .page-shell div (that width-centering div is deleted), so this now
  // targets the section itself; the same h2/testid/evidence-boundary child
  // order still holds.
  proofSectionTintedSection: '.proof-section.tinted-section',
  ragClaimRegistryArticle: '.rag-claim-registry article',
  ragDocumentVerdict: '.rag-document-verdict',
  ragHistoricalResult: '.rag-historical-result',
  ragLabLoadingError: '.rag-lab-loading.error',
  ragParseError: '.rag-parse-error',
  ragVerdict: '.rag-verdict',
  reactFlowNodeDataIdIceberg: '.react-flow__node[data-id="iceberg"]',
  reactFlowViewport: '.react-flow__viewport',
  redlineGridSpan: '.redline-grid > span',
  redlineGridSvg: '.redline-grid svg',
  relatedEngineeringEvidence: '.related-engineering-evidence',
  relatedEngineeringEvidenceAHrefAiRagQualityLab: '.related-engineering-evidence a[href^="/ai/rag-quality-lab"]',
  relatedEngineeringEvidenceAHrefAiReleaseGuardian: '.related-engineering-evidence a[href^="/ai/release-guardian"]',
  releaseApprovalGate: '.release-approval-gate',
  releaseAuditGrid: '.release-audit-grid',
  releaseAuditGridArticle: '.release-audit-grid article',
  releaseBlockerList: '.release-blocker-list',
  releaseEvalPairArticle: '.release-eval-pair article',
  releaseEvalPairArticleAggregate: '.release-eval-pair article.aggregate',
  releaseEvidenceDetailGrid: '.release-evidence-detail-grid',
  releaseEvidenceDetailGridDiv: '.release-evidence-detail-grid > div',
  releaseEvidenceProgressReached: '.release-evidence-progress .reached',
  releaseFundedStats: '.release-funded-stats',
  releaseModeLedger: '.release-mode-ledger',
  releasePlanGrid: '.release-plan-grid',
  releasePlanGridSection: '.release-plan-grid section',
  releaseReplayLoadingError: '.release-replay-loading.error',
  releaseRetrieverResult: '.release-retriever-result',
  releaseRiskScore: '.release-risk-score',
  releaseStageHeading: '.release-stage-heading',
  releaseStageHeadingStrong: '.release-stage-heading > strong',
  releaseStrictDefinition: '.release-strict-definition',
  releaseVerifiedRailList: '.release-verified-rail-list',
  releaseVerifiedRailListArticle: '.release-verified-rail-list article',
  releaseWhatChanged: '.release-what-changed',
  scopeStrong: ':scope > strong',
  // Task 1.2: secondary + archive tiers now share one hairline shelf table
  // (exhibit 05) instead of separate tier-specific lists; the contact
  // anchor is the hero exhibit itself (id="contact", spec §2.1) rather than
  // the deleted pre-rebuild .workspace-head wrapper.
  homeShelfTable: '.home-shelf-table',
  sectionContactWorkspaceHead: '#contact[data-exhibit="00"]',
  small: 'small',
  span: 'span',
  strong: 'strong',
  swapSetPanel: '.swap-set-panel',
  swapSetPanelArticle: '.swap-set-panel article',
  targetRoles: '.target-roles',
  tbodyTr: 'tbody tr',
  td: 'td',
  textarea: 'textarea',
  trackProjectsA: '.track-projects > a',
  workspaceIndexDisciplineStrip: '.workspace-index, .discipline-strip',
} as const;
